# Generated by Django 4.2.7 on 2026-01-04 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('commande_confirmee', 'Commande confirmée'), ('nouveau_message', 'Nouveau message'), ('nouvel_avis', 'Nouvel avis'), ('paiement_recu', 'Paiement reçu'), ('service_annule', 'Service annulé'), ('rappel', 'Rappel')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('lien_url', models.URLField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'est_lue'], name='notificatio_utilisa_7a669e_idx'), models.Index(fields=['utilisateur', 'date_creation'], name='notificatio_utilisa_aecdf6_idx')],
            },
        ),
    ]
