# Generated by Django 4.2.7 on 2026-01-04 03:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('disponibilite', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible'), ('en_conges', 'En congés')], default='disponible', max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_sponsorise', models.BooleanField(default=False)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('prix_promotion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_debut_promotion', models.DateTimeField(blank=True, null=True)),
                ('date_fin_promotion', models.DateTimeField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('nombre_vues', models.IntegerField(default=0)),
                ('nombre_commandes', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.categorie')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duree', models.IntegerField(blank=True, help_text='Durée en heures', null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forfaits', to='services.service')),
            ],
            options={
                'verbose_name': 'Forfait',
                'verbose_name_plural': 'Forfaits',
                'db_table': 'forfaits',
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['categorie', 'disponibilite'], name='services_categor_42a310_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['prestataire', 'est_actif'], name='services_prestat_83edda_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['ville', 'quartier'], name='services_ville_706d94_idx'),
        ),
    ]
