# Generated by Django 4.2.7 on 2026-01-04 03:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_prestataire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_escrow', 'En escrow'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('bankily', 'Bankily'), ('moov_money', 'Moov Money'), ('bamis', 'BAMIS'), ('bmci', 'BMCI'), ('carte', 'Carte bancaire')], max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=200)),
                ('transaction_id_externe', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('notes_client', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='services.service')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Abonnement Premium',
                'verbose_name_plural': 'Abonnements Premium',
                'db_table': 'abonnements_premium',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client', 'statut'], name='transaction_client__35977c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['prestataire', 'statut'], name='transaction_prestat_ff0c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['service', 'statut'], name='transaction_service_000b7b_idx'),
        ),
    ]
